version: '3'

services:
  mindustry-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - server-data:/app/config
      - server-maps:/app/maps
    restart: unless-stopped
    command: "host"

  mindustry-client:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - client-data:/root/.local/share/Mindustry
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  server-data:
  server-maps:
  client-data: