version: '3.8'

services:
  mindustry-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - server-data:/app/config
      - server-maps:/app/maps
    restart: unless-stopped
    command: "host"

  mindustry-client:
    build: .
    image: mindustry-client
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - HOME=/home/mindustry
    volumes:
      - ~/.mindustry_data:/home/mindustry
    network_mode: "host"

volumes:
  server-data:
  server-maps: